name: Build patched Go master branch for tests

on:
  workflow_dispatch:
  schedule:
    - cron: '10 14 1,16 * *'
  push:
    branches:
      - build
    paths:
      - ".github/workflows/test-go_master.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - build
    paths:
      - ".github/workflows/test-go_master.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
        buildtarget: ['master']
      fail-fast: false
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0
    steps:
      - name: Show workflow information
        run: |
          _NAME="$GOOS-$GOARCH"
          echo "GOOS: $GOOS, GOARCH: $GOARCH, APPLY-BRANCH: ${{ matrix.buildtarget }}"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Download source
        uses: actions/checkout@v6
        with:
          repository: 'golang/go'
          ref: ${{ matrix.buildtarget }}

      - name: Apply patch
        run: |
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://github.com/XTLS/go-win7/raw/refs/heads/build/patchmaster/unified-master.diff | patch --verbose -p 1

      - name: Set-up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true
          cache: false

      - name: Build patched Go
        shell: bash
        run: |
          cd ./src
          . ./make.bash "$@" --no-banner
          ../bin/go tool dist banner
          cd ..

      - name: Copy binaries into bin
        if: matrix.goos != 'linux' || matrix.goarch != 'amd64'
        shell: bash
        run: |
          cd ./bin
          DIR="${GOOS}_${GOARCH}"
          if [ -d "${DIR}" ]; then
            echo "Found ${DIR} copying binaries"
            rm ./go*
            for BINARY in "${DIR}"/*
            do
              echo "mv ./${BINARY} ./"
              mv ./${BINARY} ./
            done
            rm -r ./"${DIR}"
            rm -r ../pkg/tool/linux_amd64/
          fi
          cd ..
          ls -al ./bin

      - name: Upload package to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: go-for-win7-master-${{ env.ASSET_NAME }}
          path: |
            ./*
