name: Build patched Go 1.27 for tests

on:
  workflow_dispatch:
  schedule:
    - cron: '20 0 * * 6'
  push:
    branches:
      - build
    paths:
      - ".github/workflows/test-go1_27.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - build
    paths:
      - ".github/workflows/test-go1_27.yml"

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64, 386]
        buildtarget: ['release-branch.go1.27']
      fail-fast: false
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0
    steps:
      - name: Show workflow information
        shell: pwsh
        run: |
          $assetName = "$env:GOOS-$env:GOARCH"
          Write-Output "GOOS: $env:GOOS, GOARCH: $env:GOARCH, APPLY_BRANCH: ${{ matrix.buildtarget }}"
          "ASSET_NAME=$assetName" >> $env:GITHUB_ENV

      - name: Download source
        uses: actions/checkout@v7
        with:
          repository: 'golang/go'
          ref: ${{ matrix.buildtarget }}
          path: 'go'

      - name: Download patch
        uses: actions/checkout@v7
        with:
          path: 'patch'

      # Patches for Go 1.27.x before more minor changes introduces.
      - name: Apply patch
        shell: pwsh
        run: |
          Push-Location .\go
          patch --verbose -p 1 -i "..\patch\go-1-27.diff"
          Pop-Location

      - name: Set-up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go/src/go.mod'
          check-latest: true

      - name: Build patched Go
        shell: pwsh
        run: |
          Push-Location .\go\src
          .\make.bat --no-banner
          Pop-Location

      - name: Copy binaries into bin
        if: matrix.goos != 'windows' || matrix.goarch != 'amd64'
        shell: pwsh
        run: |
          Push-Location .\go\bin
          $targetDirectory = "${env:GOOS}_${env:GOARCH}"
          if (Test-Path -LiteralPath $targetDirectory -PathType Container) {
              Get-ChildItem -Path 'go*' | Remove-Item -Recurse -Force
              Get-ChildItem -LiteralPath $targetDirectory -Force | Move-Item -Destination .\
              Remove-Item -LiteralPath $targetDirectory -Recurse -Force
              Remove-Item -LiteralPath ..\pkg\tool\windows_amd64 -Recurse -Force
          }
          Get-ChildItem -Force
          Pop-Location

      - name: Upload package to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: go-for-win7-${{ env.ASSET_NAME }}
          path: |
            ./go/*

  source:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Download source
        uses: actions/checkout@v7
        with:
          repository: 'golang/go'
          ref: 'release-branch.go1.27'
          path: 'go'

      - name: Download patch
        uses: actions/checkout@v7
        with:
          path: 'patch'

      - name: Apply patch
        shell: pwsh
        run: |
          Push-Location .\go
          patch --verbose -p 1 -i "..\patch\go-1-27.diff"
          Pop-Location

      - name: Upload package to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: go-for-win7-source
          path: |
            ./go/*
