name: Build patched Go 1.22 for tests

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 0 * * 6'
  push:
    branches:
      - build
      - "release-branch.go1.22"
    paths:
      - ".github/workflows/test-go1_22.yml"
      - "**/*.go"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - build
      - "release-branch.go1.22"
    paths:
      - ".github/workflows/test-go1_22.yml"
      - "**/*.go"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [windows]
        goarch: [amd64]
        buildtarget: ['release-branch.go1.22']
      fail-fast: false
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0
    steps:
      - name: Show workflow information
        run: |
          _NAME="$GOOS-$GOARCH"
          echo "GOOS: $GOOS, GOARCH: $GOARCH, APPLY-BRANCH: ${{ matrix.buildtarget }}"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Download source
        uses: actions/checkout@v6
        with:
          repository: 'golang/go'
          ref: ${{ matrix.buildtarget }}

      # Patches for Go 1.22.x before more minor changes introduces.
      - name: Apply patch
        run: |
          curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://github.com/XTLS/go-win7/raw/refs/heads/build/unified-1-22-patch.diff | patch --verbose -p 1
        # curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://github.com/XTLS/go-win7/commit/e4701f06a6358bda901e72cbff44f414d902e988.diff | patch --verbose -p 1
        # curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://github.com/XTLS/go-win7/commit/41373f90356fd86e9cbe78c7a71c76066a6730c1.diff | patch --verbose -p 1
        # curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://github.com/XTLS/go-win7/commit/481cebf65c4052379cf3cda5db5588c48f2446f6.diff | patch --verbose -p 1
        # curl -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://github.com/XTLS/go-win7/commit/21d5caecf644a12d938c45f18e2b55f04b47f0b0.diff | patch --verbose -p 1

      - name: Set-up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'src/go.mod'
          check-latest: true

      - name: Build patched Go
        shell: bash
        run: |
          cd ./src
          . ./make.bash "$@" --no-banner
          "$GOTOOLDIR/dist" banner
          cd ..

      - name: Copy binaries into bin
        if: matrix.goos != 'linux' || matrix.goarch != 'amd64'
        shell: bash
        run: |
          cd ./bin
          DIR="${GOOS}_${GOARCH}"
          if [ -d "${DIR}" ]; then
            echo "Found ${DIR} copying binaries"
            rm ./go*
            for BINARY in "${DIR}"/*
            do
              echo "mv ./${BINARY} ./"
              mv ./${BINARY} ./
            done
            rm -r ./"${DIR}"
            rm -r ../pkg/tool/linux_amd64/
          fi
          cd ..
          ls -al ./bin

      - name: Upload package to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: go-for-win7-${{ env.ASSET_NAME }}
          path: |
            ./*
